app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3307/demoapi?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
    pool-size: 30
server:
  error:
    include-message: always
  port: 8081
  servlet:
    context-path: /api
spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: true